version: '3.2'


services:
    app:
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - ./diff-csv:/app
        - ./data:/usr/src/data
      working_dir: /app
      